// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// conjugate
arma::mat conjugate(arma::mat A, arma::vec b);
RcppExport SEXP _StatComp22067_conjugate(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(conjugate(A, b));
    return rcpp_result_gen;
END_RCPP
}
// f_gra1c
arma::mat f_gra1c(arma::mat x, double lambda, arma::mat s);
RcppExport SEXP _StatComp22067_f_gra1c(SEXP xSEXP, SEXP lambdaSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(f_gra1c(x, lambda, s));
    return rcpp_result_gen;
END_RCPP
}
// f_gra2c
arma::mat f_gra2c(arma::mat x, double lambda, arma::mat s);
RcppExport SEXP _StatComp22067_f_gra2c(SEXP xSEXP, SEXP lambdaSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(f_gra2c(x, lambda, s));
    return rcpp_result_gen;
END_RCPP
}
// GibbsC
NumericMatrix GibbsC(int N, double mu1, double mu2, double sigma1, double sigma2, double rho);
RcppExport SEXP _StatComp22067_GibbsC(SEXP NSEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsC(N, mu1, mu2, sigma1, sigma2, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp22067_conjugate", (DL_FUNC) &_StatComp22067_conjugate, 2},
    {"_StatComp22067_f_gra1c", (DL_FUNC) &_StatComp22067_f_gra1c, 3},
    {"_StatComp22067_f_gra2c", (DL_FUNC) &_StatComp22067_f_gra2c, 3},
    {"_StatComp22067_GibbsC", (DL_FUNC) &_StatComp22067_GibbsC, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp22067(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
