# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Conjugate Gradient method using Rcpp
#' @description Solve a system of linear equations Ax=b
#' @param A the coefficient matrix
#' @param b the augmented matrix
#' @return x0 the solution
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22067
#' @examples
#' \dontrun{
#' A = matrix(c(4,-2,-1,-2,4,-2,-1,-2,3),3)
#' b = c(0,-2,3)
#' conjugate(A,b)
#' }
#' @export
conjugate <- function(A, b) {
    .Call('_StatComp22067_conjugate', PACKAGE = 'StatComp22067', A, b)
}

#' @title Compute first-order gradient
#' @description Compute first-order gradient of the objective function
#' @param x a positive definite symmetric matrix
#' @param lambda a regularization parameter
#' @param s the sample covariance
#' @return d the first-order gradient
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22067
#' @examples
#' \dontrun{
#' f_gra1c(diag(3),1,diag(3))
#' }
#' @export
f_gra1c <- function(x, lambda, s) {
    .Call('_StatComp22067_f_gra1c', PACKAGE = 'StatComp22067', x, lambda, s)
}

#' @title Compute second-order gradient
#' @description Compute second-order gradient of the objective function
#' @param x a positive definite symmetric matrix
#' @param lambda a regularization parameter
#' @param s the sample covariance
#' @return d the second-order gradient
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22067
#' @examples
#' \dontrun{
#' f_gra2c(diag(3),1,diag(3))
#' }
#' @export
f_gra2c <- function(x, lambda, s) {
    .Call('_StatComp22067_f_gra2c', PACKAGE = 'StatComp22067', x, lambda, s)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param mu1 mean of the first random variable
#' @param mu2 mean of the second random variable
#' @param sigma1 standard deviation of the first random variable
#' @param sigma2 standard deviation of the second random variable
#' @param rho correlation of the two random variables
#' @return X random sample of size \code{n}
#' @import Rcpp
#' @useDynLib StatComp22067
#' @examples
#' \dontrun{
#' gc <- GibbsC(100)
#' par(mfrow=c(2,1));
#' plot(gc[,1],type='l')
#' plot(gc[,2],type='l')
#' }
#' @export
GibbsC <- function(N, mu1 = 0, mu2 = 0, sigma1 = 1, sigma2 = 1, rho = 0.9) {
    .Call('_StatComp22067_GibbsC', PACKAGE = 'StatComp22067', N, mu1, mu2, sigma1, sigma2, rho)
}

